name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read    # to fetch code
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  docs:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout doxygen-awesome-css submodule only
        run: git submodule update --init docs/doxygen-awesome-css
      - name: Install Doxygen and Graphviz dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Generate Doxygen docs
        run: doxygen docs/Doxyfile
      - name: Upload Doxygen HTML
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
